
# Site settings
title: INOVATIF
email: your-email@domain.com
description: We Proud To Be Young, We Proud To Be “Inovatif”

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed